language: node_js
node_js:
- node
before_deploy:
- yarn deploy
deploy:
  - provider: npm
    skip-cleanup: true
    email: "danny.wieser@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: demo
    on:
      tags: true
